language: python
python:
  - 2.7
  - 3.3
install:
  - pip install --use-mirrors cram unidecode mako Jinja2 markdown docutils Attest-latest
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors translitcodec; fi
  - python setup.py -q install
script:
  - python setup.py test && cram acrylamid/specs
branches:
  only:
    - master
    - /^feature\/.*$/
    - /^legacy\/.*$/
notifications:
  irc:
    channels:
      - "irc.freenode.org#acrylamid"
    on_success: change
    on_failure: change
    template: "%{repository} (%{commit}) : %{message}, %{build_url}"
