language: python
python:
  - 2.6
  - 2.7
install:
  - pip install --use-mirrors nose cram html2text unidecode mako
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - python setup.py -q install
script:
  - nosetests specs/
  - cram specs/
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#acrylamid"
    on_success: change
    on_failure: change
    template: "%{repository} (%{commit}) : %{message}, %{build_url}"
